### PR TITLE
Handle editing file whilst saving

### LINKED ISSUE #121: Cannot save if editing while saving
### Steps

1. Open the text editor
1. Type in something
1. Hit "ctrl+s" to save (by the way, where is my Save button?)
1. While it's still saving, type in something, then stop before it finishes the previous save
1. Hit "ctrl+s" again

### Expected result
The star should stay after it finishes saving, since we added stuff during save.

### Actual result
The star disappears and Ctrl+S doesn't save.

@tomneedham this is a regression, it worked in the old version

### PR DESCRIPTION
**Pull request by tomneedham**
- Preserves the title (doesn't prepend * each time)
 - Stops the saving message disappearing for the second save
 - Leaves the * next to the filename

To test:
 - Add a `sleep(2);` to https://github.com/owncloud/files_texteditor/blob/master/controller/filehandlingcontroller.php#L131
 - Create and open a text file
 - Add some content
 - Wait till autosave starts
 - Type some more content
 - Observe that the * stays in the filename and document title and that autosave kicks in again

Fixes #121 

@PVince81

### CODE REVIEW

**Comment by tomneedham** [comment]
(Will need backport to 8.2 branch)

**Comment by PVince81** [comment]
Works now :+1:

**Comment by PVince81** [comment]
@tomneedham can you rebase ?

**Comment by PVince81** [comment]
@karlitschek @tomneedham backport ?

**Comment by tomneedham** [comment]
I'd vote for it yes.

**Comment by karlitschek** [comment]
definitely. please backport :+1:

**Pull request merged**
