### PR TITLE
Fix Shift-JIS code misdetection

### PR DESCRIPTION
**Pull request by ghost**
I'm confirm fix Shift-JIS code misdetection ownCloud 9.0.2.
# test pattern
- Shift-JIS Japanese text file
- UTF-8 Japanese text file

Please **Merge** this and include future releases.

### CODE REVIEW

**Comment by falconws** [comment]
Relate
#46 
#51

**Comment by falconws** [comment]
@PVince81  Would you Merge this ?

**Comment by PVince81** [comment]
@falconws thanks for the PR. Not sure, is the encoding order safe ?

Had the same question when adding chinese here: https://github.com/owncloud/files_texteditor/pull/73

**Comment by PVince81** [comment]
"safe" as in "will it sometimes wrongly detect the encoding" ?

**Comment by falconws** [comment]
@PVince81 Thanks review.
I don't know what detect order safe.
And also don't know Chinese. sorry.

Do you know why concatinate $fileContents and "a" character ?

```php
mb_detect_encoding($fileContents . "a", "UTF-8, 
```

**Comment by falconws** [comment]
@PVince81 Add info

Support multibyte string
```
UTF-8, SJIS-win
```

Unsupport multibyte string
```
WINDOWS-1252, ISO-8859-15, ISO-8859-1, ASCII
```

Should be order ?
1. support multibyte string set.
2. Unsupport multibyte string set

like this
```php
mb_detect_encoding($fileContents . "a", "UTF-8, SJIS-win, 【Chinese here ?】, WINDOWS-1252, ISO-8859-15, ISO-8859-1, ASCII", true);
```

**Comment by mmattel** [comment]
Closing in favor of #333

**Pull request closed without merging**
