### PR TITLE
Adding icon to edit action in action menu

### PR DESCRIPTION
**Pull request by DeepDiver1975**
bildschirmfoto von 2015-10-12 16-15-44

@PVince81 @jancborchardt THX

### CODE REVIEW

**Comment by PVince81** [comment]
The icon looks a bit too light.

@jancborchardt ?

**Comment by jancborchardt** [comment]
Added the correct icon at https://github.com/owncloud/core/pull/19719 and changed the route here. Please re-review in combination with that core PR @DeepDiver1975 @PVince81 @owncloud/designers

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2015-10-13 00-57-10

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
