### PR TITLE
Add php 7.2 and 7.1

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@phil-davis ui tests are failing - can you please have a look? THX
https://travis-ci.org/owncloud/files_texteditor/jobs/318525161

**Comment by phil-davis** [comment]
Looking at the moment - the problem is a change in core that requires ``xmllint`` - PR coming...

**Comment by phil-davis** [comment]
If #218 fixes the infrastructure issue and is merged, then this can be rebased on top.

**Comment by phil-davis** [comment]
Rebased on top of latest master - should pass now. Let's see...

**Pull request merged**
