### PR TITLE
Implement public link support

### PR DESCRIPTION
**Pull request by JammingBen**
Also improved the loading of the app a bit in the course of this.

fixes https://github.com/owncloud/enterprise/issues/4712

### CODE REVIEW

**Comment by micbar** [comment]
Can you Unit test application.php?

**Review by phil-davis — COMMENTED** [review]
works for me. Do you want me to add a couple of acceptance test scenarios? Or do that in a later PR?

**Comment by JammingBen** [comment]
I wasn't planning to do so, feel free :)

**Comment by phil-davis** [comment]
Note: I can directly create a read-only public link share of a single text file. When I open the link, the text content of the file is displayed and there is a "Download xyz.txt" button that works. That all looks good.

I can't create a public link share of a single file with change permission. I was thinking to have a scenario where Alice creates a public link share of just a single file, with change permission, and to see how that is handled when the public link is opened - maybe the text editor could be opened to edit the file. But that kind of public link share cannot even be created - so that scenario does not happen.

**Comment by phil-davis** [comment]
Acceptance tests added for editing text files received in user, group and public link shares.
(There were not any existing scenarios for user and group shares, so I added those, as well as for public link shares)

**Review by phil-davis — APPROVED** [review]

**Comment by JanAckermann** [comment]
@phil-davis 
Currently, the files_texteditor is not responsible for displaying single shared text files, this is done by core.
I already asked PM if we should change that:
https://github.com/owncloud/enterprise/issues/4712#issuecomment-908354278

**Comment by phil-davis** [comment]
> Currently, the files_texteditor is not responsible for displaying single shared text files, this is done by core.

Good to know - my test scenario here is a double-check that the core behavior is not broken accidentally by files_texteditor.

**Pull request merged**
