### PR TITLE
Close editor when clicking outside of the container

### PR DESCRIPTION
**Pull request by tomneedham**
Fixes https://github.com/owncloud/files_texteditor/issues/132

@jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
Please review @owncloud/designers and @Instagit from the video player app just because that behaves the same. :)

**Comment by jancborchardt** [comment]
Also @tomneedham, please squash this into one commit. ;)

**Comment by tomneedham** [comment]
Will do. Just working on the code a bit.

**Comment by tomneedham** [comment]
squashed. @jancborchardt fancy a thumbs up? ;)

**Comment by jancborchardt** [comment]
Nice! :+1: 

Another review please @owncloud/designers and @Instagit

**Comment by MorrisJobke** [comment]
Tested in Chrome, Safari and Firefox :+1: works

**Comment by Instagit** [comment]
And IE10+ :+1:

**Comment by MorrisJobke** [comment]
I also just tested with IE8 and it works there too.

**Pull request merged**
