### PR TITLE
Structure for UI tests in an app

### PR DESCRIPTION
**Pull request by phil-davis**
Signed-off-by: Phil Davis <phil@jankaritech.com>

This is an example of the structure needed to make behat-selenium UI tests run in an app repo. It contains a couple of things that are not needed in a "final solution":
1) start_behat_tests.sh - this code flexibility is proposed to be added to core in https://github.com/owncloud/core/pull/28117 - if that happens, then start_behat_tests.sh will no longer be needed here, and code here that calls it can be adjusted to call the version in core.
2) an example "feature" called "loginz" is provided just to demonstrate that something real can run as a behat-selenium test. This is just the "login" feaure from core, renamed :) If/when a real UI test(s) is written for this repo, then that test's feature etc files would go in here.

For the Travis Saucelabs job to run successfully from this repo, it needs to have SAUCE_USERNAME and SAUCE_ACCESS_KEY env vars set up in the travis-ci.org settings for this repo. I did that in my own fork of this repo (using my own SauceLabs authentication) and it works.

### CODE REVIEW

**Comment by phil-davis** [comment]
This now uses the "more flexible" start_behat_tests.sh from core that was committed today.
It works from my fork of this repo, which has SauceLabs access set up.
The Travis-CI fails from here because the owncloud/files_texteditor repo does not have the SauceLabs authentication env vars set up.

**Comment by butonic** [comment]
@tboerger what are the options of running selenium tests?

Can we make the selenium tests visible as a dedicated check and make it optional for now?

**Comment by tboerger** [comment]
> Can we make the selenium tests visible as a dedicated check and make it optional for now?

Not with travis, but we can create Jenkins jobs for that.

**Comment by phil-davis** [comment]
I am happy to provide whatever input, but for a Jenkins setup that fires up the whole selenium etc environment then that would be a devops thing.
Just note that for the public apps, it is easy to run automated UI tests on Travis plus SauceLabs. They will run just like they do in core and use as much common code from core as possible. And since apps are typically smaller than core, the UI tests should not take long to run.

**Comment by tboerger** [comment]
True, SauceLabs should be an option as well

**Comment by PVince81** [comment]
What's the next step ? Add the saucelabs creds in Travis ? @DeepDiver1975

**Comment by phil-davis** [comment]
@PVince81 @DeepDiver1975 if somebody adds the SauceLabs creds to Travis for this repo then I can make some basic demonstration UI test happen. At least that will make the framework of this visible as a working example.
Then after discussion of testing/QA priorities, it can be decided whether adding more UI test coverage here, or in some other app(s) is more important.

**Comment by phil-davis** [comment]
See #204 for the code that does real text editor tests.

**Pull request closed without merging**
