### PR TITLE
Add yaml to file actions

### PR DESCRIPTION
**Pull request by muja**
A YAML file will be downloaded instead of edited when opened from the files app. This pull request will instead try to edit the file.

### CODE REVIEW

**Comment by felixboehm** [comment]
:+1:

**Comment by felixboehm** [comment]
@MorrisJobke

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@karlitschek Can we backport this?

**Comment by MorrisJobke** [comment]
@muja Just forgot something:

Thanks a lot for your contribution!
Contributions to the core repo require a signed contributors agreement http://owncloud.org/about/contributor-agreement/

Alternatively you can add a comment here where you state that this contribution is MIT licensed.

**Comment by muja** [comment]
This contribution is MIT licensed.

**Comment by karlitschek** [comment]
nice :+1: 
Please backport

**Pull request merged**
