### PR TITLE
Update file size in list when closing editor

### PR DESCRIPTION
**Pull request by tomneedham**
Fixes https://github.com/owncloud/files_texteditor/issues/133

@butonic

### CODE REVIEW

**Comment by butonic** [comment]
tested in chromium. works like a charm :+1:

**Comment by butonic** [comment]
cc @MorrisJobke for a quick review

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@tomneedham Can you create the backport PR, because this was scheduled for 8.2.1

cc @karlitschek @cmonteroluque

**Pull request merged**
