### PR TITLE
Update file size in list when closing editor

### PR DESCRIPTION
**Pull request by tomneedham**
Backport of https://github.com/owncloud/files_texteditor/pull/134 to stable 8.2

@MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@karlitschek Please approve this ;) It was scheduled for 8.2.1 ;)

**Comment by MorrisJobke** [comment]
cc @butonic

**Comment by karlitschek** [comment]
backport is fine :+1:

**Pull request merged**
