### PR TITLE
Do not show actual error message

### PR DESCRIPTION
**Pull request by LukasReschke**
In case of not existant files this could leak informations such as the full path.

Fixes https://github.com/owncloud/security-tracker/issues/180

### CODE REVIEW

**Comment by LukasReschke** [comment]
stable8.1 backport: https://github.com/owncloud/files_texteditor/pull/97

cc @schiesbn @karlitschek @DeepDiver1975

**Comment by LukasReschke** [comment]
Patch has been confirmed by reporter.

**Comment by nickvergessen** [comment]
Well would be nice to see the error. Can't we just strip out the path?

**Comment by LukasReschke** [comment]
> Well would be nice to see the error. Can't we just strip out the path?

Agreed on needing to adjust the exception, I do however think we should in this case also do this since the exceptions thrown at this point are rather cryptic anyways and not understood by regular users. Stuff like "File is already deleted" and so on is catched before. So we're left with cryptic errors such as "Can't create lock type 1 on /bar/foo".

So I will adjust the exception in core as well if possible but this should IMHO stay as well. Also since this is an easier to fix issue :)

**Comment by tomneedham** [comment]
:+1:

**Pull request merged**
