### PR TITLE
Remove unused extensions

### PR DESCRIPTION
**Pull request by tomneedham**
Free up some space :) Let the mode-list extension in as it has a more comprehensive list of supported syntaxes that we maintain individually so swapping over to that seems more sensible.

@PVince81 @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
Needs rebase :smile:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by jancborchardt** [comment]
@PVince81 can this be merged then?

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
