### PR TITLE
Fix issue #58: Text editor freezes when trying to load non-existing share...

### PR DESCRIPTION
**Pull request by rzg-kaiser**
Pull request for issue #58 as requested.
A mentioned in the issue tracker, we should still try to get a sensible error message from somewhere (loadfile.php?).

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@PVince81 @MorrisJobke please review this PR - fixing this for 8.1 might be an option. THX

**Comment by PVince81** [comment]
I believe that @schiesbn fixed something similar here yesterday: https://github.com/owncloud/files_texteditor/pull/72

@schiesbn can you confirm whether your fix is the same as this one here ?

**Comment by MorrisJobke** [comment]
This fixes the issue. The response needs to be adjusted too, but this handles error cases properly in the client side code. 

@PVince81 #72 is still needed for the server fixes (to have a proper response and be able to show a proper error message)

:+1:

**Comment by MorrisJobke** [comment]
@nickvergessen @LukasReschke Can you please review. Steps are at https://github.com/owncloud/files_texteditor/issues/58#issuecomment-76589148

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
