### PR TITLE
Fix for #192

### PR DESCRIPTION
**Pull request by ahmedabt**
1) Added ".cmd" and ".bat" file extensions
2) fixed powershell extension file extension

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Failing travis can be ignored - no related

**Comment by PVince81** [comment]
To be merged next week after the freeze

**Comment by PVince81** [comment]
Argh no, this is for master, not maintenance releases. Open for merging then.

**Comment by DeepDiver1975** [comment]
hmmm .... bat file cannot be opened by clicking it - strange

**Comment by DeepDiver1975** [comment]
> hmmm .... bat file cannot be opened by clicking it - strange

bat and cmd files are detected as application/octet-stream - should be text ....

**Comment by DeepDiver1975** [comment]
:+1: but this change in itself works :+1: 

THX @ahmedabt

**Comment by ahmedabt** [comment]
I will try to debug the reason why they are detected as application/octet-stream and feedback in case I found any clue

**Comment by DeepDiver1975** [comment]
> I will try to debug the reason why they are detected as application/octet-stream and feedback in case I found any clue

this is basically fixed with #190

**Comment by ahmedabt** [comment]
what's the due date for milestone 10.0?

**Pull request merged**
