### PR TITLE
Place editor inside of app-content

### LINKED ISSUE #61: text editor is placed on the slide menu
On mobile view (oc8) the text editor is placed in the auto-hide sliding menu on the left so its only viewable (and only the half of it) when you slide to the right.

### PR DESCRIPTION
**Pull request by Henni**
fixes #61; replaces #92 

cc @MorrisJobke 
@eephyne please check if you can scroll the editor now

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works a lot better now :+1:

**Comment by MorrisJobke** [comment]
cc @rullzer @Xenopathic please test also :)

**Comment by Xenopathic** [comment]
Tested, works :+1:

**Comment by eephyne** [comment]
Can't test it I'm not on 8.1 (8.0.4). But I can guess it's OK since it seem to be fine for everyone else

**Pull request merged**
