### PR TITLE
fix "Shift JIS" code misdetection

### PR DESCRIPTION
**Pull request by papillon326**
see https://github.com/owncloud/files_texteditor/issues/46

### CODE REVIEW

**Comment by jancborchardt** [comment]
Can you please review this @falconws @ukitiyan @shimarin @tomneedham

**Comment by falconws** [comment]
@jancborchardt I review'd.
When this patch apply Production(ownCloud 8.2) Release Channel ?

**Comment by jancborchardt** [comment]
@tomneedham can you take care?

**Comment by falconws** [comment]
Please Merge this pull request.

By the way, ownCloud Ver 8.1(?) changed file construction
```
/apps/files_texteditor/controller/filehandlingcontroller.php
```

**Comment by mmattel** [comment]
Closing in favor of #333

**Pull request closed without merging**
