### PR TITLE
vanish notification about unsaved changes after a period of time

### PR DESCRIPTION
**Pull request by MorrisJobke**
fixes https://github.com/owncloud/core/issues/11412

The message vanishes after 7 seconds (I just used the default timeout)

cc @jancborchardt @PVince81 @jnfrmarks

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@tomneedham You're the official maintainer of this app :P

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975 @LukasReschke

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
but still the logic seems odd to me @jancborchardt

**Comment by jancborchardt** [comment]
@DeepDiver1975 what do you mean by that? Like, in this case it might be better to have it stay until other changes are made instead of timeouting?

**Comment by DeepDiver1975** [comment]
Letting the user close the editor and tell him about unsaved changes.

Better from my pov would be to tell him this fact before leaving the editor.

**Comment by tomneedham** [comment]
> Better from my pov would be to tell him this fact before leaving the editor.

I thought the ethos was to provide an undo, instead of asking for a confirmation that gets ignored super easily

**Comment by tomneedham** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Um … when you close the editor and there are unsaved changes in the document, they should of course be automatically saved.

Undo is not relevant in this case cause you expect it to be saved automatically of course.

**Pull request merged**
